
version: "3"

services:
   backend:
      build: ./php
   frontend:
      build: ./public_html
      ports:
         - "80:80"
         - "443:443"
      volumes:
         - ./production.conf:/etc/nginx/conf.d/default.conf
         - ./public_html:/usr/share/nginx/html
         - ./dh-param:/etc/ssl/certs
         - /docker-volumes/pwp/etc/letsencrypt/live/atilahundun.net/fullchain.pem:/etc/letsencrypt/live/atilahundun.net/fullchain.pem
         - /docker-volumes/pwp/etc/letsencrypt/live/atilahundun.net/privkey.pem:/etc/letsencrypt/live/atilahundun.net/privkey.pem